AWSTemplateFormatVersion: '2010-09-09'
Description: 'A CloudFormation Stack to create S3 bucket, EC2 Instance Bootstrapped with Jenkins and Security group'

Parameters:
  BucketName:
    Description: 'Name of the S3 bucket, which must be globally unique'
    Type: String

  EncryptionType:
    Description: 'Encryption type for the S3 bucket (SSE-S3 or KMS)'
    Type: String
    Default: SSE-S3
    AllowedValues:
      - SSE-S3
      - KMS

Conditions:
  IsSSES3:
    !Equals [!Ref EncryptionType, SSE-S3]
  IsKMS:
    !Equals [!Ref EncryptionType, KMS]

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !If [IsSSES3, AES256, aws:kms]
              KMSMasterKeyID: !If [IsKMS, !Ref KMSKeyID, !Ref 'AWS::NoValue']

Outputs:
  S3Bucket:
    Description: 'S3 bucket created using this template'
    Value: !Ref S3Bucket